# Generated by Django 4.2.4 on 2024-07-12 21:05

from django.db import migrations, models
import epdb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpdbEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proces', models.CharField(max_length=200)),
                ('ligand_file', models.FileField(upload_to=epdb.models.docking_directory_path)),
                ('receptor_file', models.FileField(upload_to=epdb.models.docking_directory_path)),
                ('gridsize', models.CharField(blank=True, max_length=200)),
                ('gridcenter', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
