version: '3.8'

services:

  django:
    build: .
    command: >
      sh -c "env
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/www/server
      - user_data:/var/www/biodocking
    ports:
      - "8000:8000"
    

volumes:  
  user_data:

